# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-19 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import shopapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类名称')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='产品名字')),
                ('image', models.ImageField(blank=True, upload_to=shopapp.models.upload_image)),
                ('prince', models.IntegerField(verbose_name='产品价格')),
                ('description', models.CharField(max_length=200, verbose_name='产品价格')),
                ('addtime', models.DateField()),
                ('kind', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopapp.Category', verbose_name='产品分类')),
            ],
        ),
    ]
